use_recurrent_policy: False
clip_param: 0.2
ppo_epoch: 5
num_mini_batch: 4
value_loss_coef: 0.5
entropy_coef: 0.01
lr: 0.0003
eps: 0.00001
max_grad_norm: 0.5
num_env_steps: 10000000
num_steps: 250
use_gae: True
gamma: 0.99
gae_lambda: 0.95
use_proper_time_limits: True
save_interval: 100
use_linear_lr_decay: True